### ISSUE TITLE
`time_radius` mechanism

### ISSUE THREAD

**Issue by jbmelander** [flatironinstitute/mountainsort5#17]
@magland My understanding is that in order for a spike to be grabbed and clustered, it has to be free of any spikes within the `time_radius` in `detect_spikes.py` - if this is correct, then looking at autocorrelations becomes somewhat uninformative because refractory period violations are specifically excluded from the get-go. Historically, we've clustered all cells, regardless of such violations, then used the autocorrelation as a means of describing how well the clustering behaved. Could you comment on whether my understanding is correct?

**Comment by magland** [comment]
Yes your thinking is correct. So that's why it's important to choose time_radius to be short relative to the refractory period. I believe the default is 0.5 ms, whereas the refractory period is more like 2ms. So there should always be a 0.5 radius dip, but you can also look for the 2-3 ms dip for validation.

**Comment by magland** [comment]
> edit: Is it just a way to enure only a single threshold-crossing is flagged despite the threshold crossing for many samples during the duration of the spike?

Yes that's exactly it.
